version: '2.0'
services:
    # database
    budget_app_db:
        container_name: budget_app_db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: budgetapp_db_password
            MYSQL_DATABASE: budget_app
        ports:
            - '3307:3306'
        volumes:
            - './databases/data:/var/lib/mysql'
        networks:
            - budget_app_network

    budget_app:
        container_name: budget_app
        build: ./app/
        restart: always
        ports:
            - '3000:3000'
        command: npm run dev
        volumes:
            - ./app/:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
          - budget_app_db
        networks:
            - budget_app_network

networks:
    budget_app_network:
        external: true
