version: "2"
services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - zuul
  food_service:
    container_name: food_service
    build: ./food_service/
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - food_service_db
      - eureka
      - zuul
  food_service_db:
    container_name: food_service_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: food_service_password
      MYSQL_DATABASE: food_service
    ports:
      - "3307:3306"
  eureka:
    container_name: eureka
    build: ./service_discovery/eureka/
    ports:
      - "9091:9091"
  zuul:
    container_name: zuul
    build: ./service_discovery/zuul/
    ports:
      - "9092:9092"
    depends_on:
      - eureka
