version: "2"
services:
  redis:
    container_name: redis
    image: redis:5.0.5
    restart: always
    ports:
      - "6379:6379"
    networks:
      - "budget_app_network"
networks:
  budget_app_network:
    external: true