version: "2"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - budget_app_network
  logstash:
    container_name: logstash
    image: logstash:7.2.0
    networks:
      - budget_app_network
  kibana:
    container_name: kibana
    image: kibana:7.2.0
    ports:
      - "5601:5601"
    networks:
      - budget_app_network
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7
    ports:
      - "15672:15672"
    networks:
      - budget_app_network
networks:
  budget_app_network:
    external: true