version: "2"
services:
  budget_app_db:
    container_name: budget_app_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: budgetapp_db_password
      MYSQL_DATABASE: budget_app
    ports:
      - "3307:3306"
    volumes:
      - "./data:/var/lib/mysql"
      - "./docker/provision/mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - budget_app_network
networks:
  budget_app_network:
    external: true
